version: '3.8'

services:
  api:
    command: npm run start
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cumes-api
    env_file:
      - .env.development
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend/assets:/usr/src/app/assets
    networks:
      - cumes-network

  postgres:
    image: postgres:16-alpine
    container_name: cumes-postgres
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - cumes-network

volumes:
  db-data:

networks:
  cumes-network:
    driver: bridge
